### ISSUE TITLE
Login funktioniert nicht

### ISSUE THREAD

**Issue by Erlomt** [MasterPhil99/StammdatenbereitstellungTdoT#1]
/login verlangt eine uuid

leider ist eine Authentifizierung nicht möglich.

Request URL:http://127.0.0.1:3000/login
Request Method:GET
Status Code:401 Unauthorized

Response:
{
          "info": "UUID must be set",
          "link": "http://127.0.0.1:3000"
}

**Comment by Farag42** [comment]
fixed
